Repository bioimage-io/spec-bioimage-io, pull requests merged in 2021-07, with the labels that each got.

#157 Remove pickle
  bioimageio/spec/v0_3/schema.py
Labels: removal

#162 fix bioimageio entry point
  setup.py
Labels: bug

#166 fix complaint -> compliant
  README.md
  bioimageio/spec/v0_3/schema.py
Labels: bug, documentation

#167 use test inputs/outputs also as sample
  example_specs/models/unet2d_nuclei_broad/rdf.yaml
  example_specs/models/unet2d_nuclei_broad/rdf_v0_1_0.yaml
  example_specs/models/unet2d_nuclei_broad/rdf_v0_3_0.yaml
  example_specs/models/unet2d_nuclei_broad/rdf_v0_3_1.yaml
Labels: testing

#165 add static data via manifest
  MANIFEST.in
  bioimageio/spec/VERSION
  setup.py
Labels: enhancement

#155 Fix the restriction on type key for general RDF
  bioimageio/spec/v0_3/raw_nodes.py
Labels: bug

#169 update readme with conda install
  README.md
Labels: documentation

#176 Generate the supported_weight_formats key
  scripts/generate_weights_formats_overview.py
Labels: enhancement

#175 Fix general spec version in README
  README.md
  scripts/generate_json_specs.py
Labels: bug, documentation

#182 add weights_format to package file name
  bioimageio/spec/shared/io.py
Labels: enhancement

#184 Improve change log
  README.md
Labels: documentation

#183 Fix generated general spec markdown file name
  scripts/generate_docs.py
Labels: bug

#186 Update generate_json_specs.py
  README.md
  scripts/generate_docs.py
  scripts/generate_json_specs.py
Labels: documentation

#188 Update README.md
  README.md
Labels: documentation

#193 Add float32 requirement to preprocessing
  supported_formats_and_operations.md
Labels: documentation, enhancement

#197 add weights_priority_order to load_node
  bioimageio/spec/delegator.py
  bioimageio/spec/shared/io.py
Labels: enhancement

#200 Fix export uri string
  bioimageio/spec/shared/utils.py
Labels: bug

#207 add test_fields.TestURI
  tests/test_fields.py
Labels: enhancement, testing
