Repository bioimage-io/spec-bioimage-io, pull requests merged in 2021-09, with the labels that each got.

#226 Make bioimageio.spec purely about the spec
  bioimageio/spec/__init__.py
  bioimageio/spec/__main__.py
  bioimageio/spec/commands.py
  bioimageio/spec/delegator.py
  bioimageio/spec/exceptions.py
  bioimageio/spec/io_.py
  bioimageio/spec/model/__init__.py
  bioimageio/spec/model/base_nodes.py
  bioimageio/spec/model/nodes.py
  bioimageio/spec/model/v0_1/__init__.py
  bioimageio/spec/model/v0_1/nodes.py
  bioimageio/spec/model/v0_1/utils.py
  bioimageio/spec/model/v0_3/__init__.py
  bioimageio/spec/model/v0_3/base_nodes.py
  bioimageio/spec/model/v0_3/converters.py
  bioimageio/spec/model/v0_3/nodes.py
  bioimageio/spec/model/v0_3/raw_nodes.py
  bioimageio/spec/model/v0_3/schema.py
  bioimageio/spec/model/v0_3/utils.py
  bioimageio/spec/rdf/__init__.py
  bioimageio/spec/rdf/base_nodes.py
  bioimageio/spec/rdf/nodes.py
  bioimageio/spec/rdf/v0_2/__init__.py
  bioimageio/spec/rdf/v0_2/base_nodes.py
  bioimageio/spec/rdf/v0_2/nodes.py
  bioimageio/spec/rdf/v0_2/raw_nodes.py
  bioimageio/spec/rdf/v0_2/schema.py
  bioimageio/spec/rdf/v0_2/utils.py
  bioimageio/spec/shared/__init__.py
  bioimageio/spec/shared/base_nodes.py
  bioimageio/spec/shared/common.py
  bioimageio/spec/shared/io_.py
  bioimageio/spec/shared/nodes.py
  bioimageio/spec/shared/raw_nodes.py
  bioimageio/spec/shared/utils.py
  scripts/generate_docs.py
  scripts/generate_weights_formats_overview.py
  tests/conftest.py
  tests/test_base_nodes.py
  tests/test_commands.py
  tests/test_dump_spec.py
  tests/test_export_package.py
  tests/test_format_version_conversion.py
  tests/test_load_rdf.py
  tests/test_raw_load_resource_description.py
  tests/test_schemas.py
  tests/test_utils.py
  tests/test_versions/test_v0_1.py
  tests/test_weights_formats.py
  tests/test_yaml.py
Labels: documentation, ci, github_actions

#229 add test_replace_uri_wo_uri_string
  bioimageio/spec/shared/raw_nodes.py
  tests/test_raw_nodes.py
Labels: enhancement, testing

#233 More examples
  example_specs/models/unet2d_diff_output_shape/cover.jpg
  example_specs/models/unet2d_diff_output_shape/documentation.md
  example_specs/models/unet2d_diff_output_shape/environment.yaml
  example_specs/models/unet2d_diff_output_shape/rdf.yaml
  example_specs/models/unet2d_diff_output_shape/resize_unet.py
  example_specs/models/unet2d_diff_output_shape/test_input.npy
  example_specs/models/unet2d_diff_output_shape/test_output.npy
  example_specs/models/unet2d_diff_output_shape/weights.pt
  example_specs/models/unet2d_fixed_shape/cover.jpg
  example_specs/models/unet2d_fixed_shape/documentation.md
  example_specs/models/unet2d_fixed_shape/environment.yaml
  example_specs/models/unet2d_fixed_shape/rdf.yaml
  example_specs/models/unet2d_fixed_shape/test_input.npy
  example_specs/models/unet2d_fixed_shape/test_output.npy
  example_specs/models/unet2d_fixed_shape/unet.py
  example_specs/models/unet2d_fixed_shape/weights.pt
  example_specs/models/unet2d_multi_tensor/cover.jpg
  example_specs/models/unet2d_multi_tensor/documentation.md
  example_specs/models/unet2d_multi_tensor/environment.yaml
  example_specs/models/unet2d_multi_tensor/multi_tensor_unet.py
  example_specs/models/unet2d_multi_tensor/rdf.yaml
  example_specs/models/unet2d_multi_tensor/test_input_0.npy
  example_specs/models/unet2d_multi_tensor/test_input_1.npy
  example_specs/models/unet2d_multi_tensor/test_output_0.npy
  example_specs/models/unet2d_multi_tensor/test_output_1.npy
  example_specs/models/unet2d_multi_tensor/weights.pt
  tests/conftest.py
  tests/test_raw_load_resource_description.py
Labels: documentation

#239 polish up pre- and postprocessing tests and schemas
  bioimageio/spec/model/v0_3/schema.py
  bioimageio/spec/shared/fields.py
  tests/test_schema.py
  tests/test_schema_model.py
  tests/test_schemas.py
  tests/test_schemas_input_output_tensors.py
  tests/test_schemas_processing.py
Labels: testing

#244 fix kwargs annotations in raw_nodes
  bioimageio/spec/model/v0_3/raw_nodes.py
Labels: bug

#248 remove SpecURI from model v0.1
  bioimageio/spec/model/v0_1/schema.py
  bioimageio/spec/model/v0_3/schema.py
  bioimageio/spec/shared/fields.py
Labels: removal
