Repository bioimage-io/spec-bioimage-io, pull requests merged in 2021-11, with the labels that each got.

#269 Add --version option to CLI
  bioimageio/spec/__main__.py
Labels: enhancement

#272 Generate pre-/postprocessing docs
  .github/workflows/build.yml
  .github/workflows/post-merge-cleanup.yaml
  bioimageio/spec/model/v0_3/schema.py
  bioimageio/spec/shared/fields.py
  bioimageio/spec/shared/schema.py
  scripts/generate_processing_docs.py
Labels: ci, github_actions

#271 bump patch
  README.md
  bioimageio/spec/VERSION
Labels: documentation

#275 generate more docs and use them
  .github/workflows/build.yml
  .pre-commit-config.yaml
  bioimageio/spec/model/v0_3/raw_nodes.py
  bioimageio/spec/model/v0_3/schema.py
  bioimageio/spec/shared/fields.py
  scripts/generate_processing_docs.py
  scripts/generate_rdf_docs.py
  scripts/generate_weight_formats_docs.py
  scripts/generate_weight_formats_overview.py
  setup.py
  supported_formats_and_operations.md
Labels: documentation, ci, github_actions

#284 Add halo to stardist example model
  example_specs/models/stardist_example_model/rdf.yaml
Labels: enhancement

#287 Fix build package with relative paths not strings
  bioimageio/spec/shared/fields.py
  bioimageio/spec/shared/utils.py
Labels: bug

#279 add anchors to RDF docs
  scripts/generate_rdf_docs.py
Labels: enhancement

#293 fix relative paths in RawNodePackageTransformer
  bioimageio/spec/io_.py
  bioimageio/spec/shared/utils.py
Labels: bug

#294 add and use YamlDict
  bioimageio/spec/model/v0_3/schema.py
  bioimageio/spec/rdf/v0_2/schema.py
  bioimageio/spec/shared/fields.py
Labels: enhancement

#303 v0.4 impl fixes
  bioimageio/spec/model/__init__.py
  bioimageio/spec/model/v0_1/schema.py
  bioimageio/spec/model/v0_3/raw_nodes.py
  bioimageio/spec/model/v0_3/schema.py
  bioimageio/spec/model/v0_4/raw_nodes.py
  bioimageio/spec/model/v0_4/schema.py
  bioimageio/spec/shared/fields.py
  scripts/generate_weight_formats_docs.py
  tests/test_fields.py
  tests/test_raw_nodes_match_schema.py
Labels: bug

#306 Minor validation fixes
  bioimageio/spec/model/v0_4/schema.py
  bioimageio/spec/rdf/v0_2/schema.py
  tests/test_schema_model.py
Labels: bug
