Repository bioimage-io/spec-bioimage-io, pull requests merged in 2021-12, with the labels that each got.

#304 Remove Fiji from the consumer
  scripts/generate_weight_formats_overview.py
Labels: removal

#308 Fix attachments
  bioimageio/spec/model/v0_4/raw_nodes.py
  bioimageio/spec/model/v0_4/schema.py
  bioimageio/spec/rdf/v0_2/schema.py
  bioimageio/spec/shared/schema.py
  tests/test_raw_load_resource_description.py
Labels: bug

#309 Add maintainers field
  bioimageio/spec/model/v0_4/raw_nodes.py
  bioimageio/spec/model/v0_4/schema.py
  bioimageio/spec/shared/fields.py
  tests/test_schema_model.py
Labels: enhancement

#312 Add support for real zenodo doi
  bioimageio/spec/io_.py
  bioimageio/spec/model/v0_4/converters.py
  tests/test_commands.py
Labels: enhancement

#310 bump version
  README.md
  bioimageio/spec/VERSION
Labels: documentation

#321 Fix attachment files
  bioimageio/spec/model/v0_4/raw_nodes.py
Labels: bug

#323 Improve merged PR cleanup
  .github/workflows/post-merge-cleanup.yaml
Labels: ci, github_actions

#334 bump post version
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/collection/v0_2/schema.py
  bioimageio/spec/io_.py
  bioimageio/spec/model/v0_4/schema.py
Labels: documentation

#335 Add update_to_format kwarg and improve changelog
  README.md
  bioimageio/spec/__main__.py
  bioimageio/spec/commands.py
  bioimageio/spec/io_.py
  example_specs/models/unet2d_nuclei_broad/rdf_v0_3_4.yaml
  tests/conftest.py
  tests/test_raw_load_resource_description.py
Labels: documentation, enhancement

#337 refine test_load_raw_model_to_format
  tests/test_raw_load_resource_description.py
Labels: testing

#338 Bump version
  README.md
  bioimageio/spec/VERSION
Labels: documentation

#278 Update halo description
  .github/workflows/build.yml
  bioimageio/spec/model/v0_3/schema.py
  bioimageio/spec/shared/utils.py
  scripts/generate_processing_docs.py
Labels: ci, github_actions

#339 Update README.md
  README.md
Labels: documentation

#345 remove model spec 0.1
  bioimageio/spec/model/__init__.py
  bioimageio/spec/model/v0_1/__init__.py
  bioimageio/spec/model/v0_1/converters.py
  bioimageio/spec/model/v0_1/raw_nodes.py
  bioimageio/spec/model/v0_1/schema.py
  bioimageio/spec/model/v0_1/utils.py
  bioimageio/spec/model/v0_3/converters.py
  bioimageio/spec/model/v0_4/converters.py
  example_specs/models/unet2d_nuclei_broad/rdf_v0_1_0.yaml
  scripts/generate_json_specs.py
  scripts/generate_rdf_docs.py
  tests/conftest.py
Labels: removal

#349 Fix collection spec validation
  bioimageio/spec/__main__.py
  bioimageio/spec/collection/v0_2/raw_nodes.py
  bioimageio/spec/commands.py
  bioimageio/spec/shared/common.py
Labels: bug, enhancement

#356 Various fixes for general RDF and Collection RDF
  bioimageio/spec/collection/v0_2/raw_nodes.py
  bioimageio/spec/collection/v0_2/schema.py
  bioimageio/spec/commands.py
  bioimageio/spec/rdf/v0_2/raw_nodes.py
  tests/test_cli.py
  tests/test_commands.py
Labels: bug

#358 Bump version
  README.md
  bioimageio/spec/VERSION
Labels: documentation

#360 bump version
  README.md
  bioimageio/spec/VERSION
Labels: documentation

#361 remove assumptions in model 0.3 converters
  bioimageio/spec/model/v0_3/converters.py
Labels: removal

#362 Fix serialize dataset
  bioimageio/spec/shared/common.py
  bioimageio/spec/shared/utils/_resolve_source.py
  example_specs/models/unet2d_nuclei_broad/rdf_v0_3_0.yaml
  example_specs/models/unet2d_nuclei_broad/rdf_v0_3_1.yaml
  tests/test_dump_spec.py
Labels: bug
