Repository bioimage-io/spec-bioimage-io, pull requests merged in 2021-08, with the labels that each got.

#212 Remove ruamel.yaml dependency
  README.md
  bioimageio/spec/shared/common.py
  scripts/compare_yaml_syntax.py
  setup.py
  tests/conftest.py
  tests/test_format_version_conversion.py
  tests/test_utils.py
  tests/test_yaml.py
Labels: documentation, removal

#213 Fix bioengine documentation link
  README.md
Labels: bug, documentation

#222 show diff if black goes wrong
  .github/workflows/build.yml
Labels: ci, github_actions
