Repository bioimage-io/spec-bioimage-io, pull requests merged in 2022-01, with the labels that each got.

#365 Simplify collection RDF
  .github/workflows/build.yml
  README.md
  bioimageio/spec/collection/v0_2/converters.py
  bioimageio/spec/collection/v0_2/raw_nodes.py
  bioimageio/spec/collection/v0_2/schema.py
  bioimageio/spec/commands.py
  bioimageio/spec/model/v0_3/converters.py
  bioimageio/spec/model/v0_3/raw_nodes.py
  bioimageio/spec/model/v0_4/converters.py
  bioimageio/spec/model/v0_4/raw_nodes.py
  bioimageio/spec/rdf/v0_2/converters.py
  bioimageio/spec/rdf/v0_2/raw_nodes.py
  bioimageio/spec/rdf/v0_2/schema.py
  bioimageio/spec/shared/fields.py
  bioimageio/spec/shared/schema.py
  bioimageio/spec/shared/utils/_resolve_source.py
  example_specs/collections/unet2d_nuclei_broad_coll/README.md
  example_specs/collections/unet2d_nuclei_broad_coll/cover0.png
  example_specs/collections/unet2d_nuclei_broad_coll/environment.yaml
  example_specs/collections/unet2d_nuclei_broad_coll/rdf.yaml
  example_specs/collections/unet2d_nuclei_broad_coll/test_input.npy
  example_specs/collections/unet2d_nuclei_broad_coll/test_output.npy
  example_specs/collections/unet2d_nuclei_broad_coll/unet2d.py
  example_specs/collections/unet2d_nuclei_broad_coll/weights.onnx
  example_specs/collections/unet2d_nuclei_broad_coll/weights.pt
  example_specs/models/unet2d_nuclei_broad/rdf.yaml
  tests/conftest.py
  tests/test_commands_with_collection.py
Labels: documentation, ci, github_actions

#368 add missing id and rdf_source to raw_nodes
  bioimageio/spec/rdf/v0_2/raw_nodes.py
  tests/test_dump_spec.py
Labels: enhancement

#371 hotfix missing requests
  bioimageio/spec/VERSION
  bioimageio/spec/shared/utils/_docs.py
Labels: bug

#375 Make some fields optional in the general RDF
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/collection/v0_2/raw_nodes.py
  bioimageio/spec/rdf/v0_2/raw_nodes.py
  bioimageio/spec/rdf/v0_2/schema.py
  example_specs/collections/unet2d_nuclei_broad_coll/rdf.yaml
  example_specs/rdf-examples.md
Labels: documentation

#377 Small fix in the README
  README.md
Labels: bug, documentation

#376 document update-format command
  README.md
Labels: documentation

#380 bump patch and small fixes
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/rdf/v0_2/raw_nodes.py
Labels: bug, documentation

#382 add field `download_url` to model RDF
  README.md
  bioimageio/spec/model/v0_4/schema.py
  bioimageio/spec/rdf/v0_2/raw_nodes.py
  bioimageio/spec/rdf/v0_2/schema.py
  example_specs/models/unet2d_nuclei_broad/rdf.yaml
  tests/test_format_version_conversion.py
Labels: documentation, enhancement

#384 Add the validator plugin for the uploader
  scripts/bio-rdf-validator.imjoy.html
Labels: enhancement

#385 fix transform missing values
  bioimageio/spec/shared/utils/_node_transformer.py
Labels: bug
