Repository bioimage-io/spec-bioimage-io, pull requests merged in 2022-05, with the labels that each got.

#438 resolve symlinks when transforming absolute to relative paths during serialization
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/shared/node_transformer.py
  tests/test_dump_spec.py
Labels: documentation, enhancement, testing

#441 Limit cache warnings and document environment variables
  README.md
  bioimageio/spec/__init__.py
  bioimageio/spec/commands.py
  bioimageio/spec/shared/_resolve_source.py
  bioimageio/spec/shared/common.py
Labels: documentation

#443 Robust abs to rel paths
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/shared/node_transformer.py
Labels: documentation

#444 create bioimageio.spec.partner
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/__main__.py
  bioimageio/spec/collection/v0_2/utils.py
  bioimageio/spec/commands.py
  bioimageio/spec/partner/__init__.py
  bioimageio/spec/partner/imjoy_plugin_parser.py
  bioimageio/spec/partner/utils.py
Labels: documentation

#447 allow root_path to be URI
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/io_.py
  bioimageio/spec/shared/_resolve_source.py
  bioimageio/spec/shared/node_transformer.py
  bioimageio/spec/shared/raw_nodes.py
  tests/test_node_transformer.py
  tests/test_raw_nodes.py
Labels: documentation

#448 pass root to enrich_partial_rdf
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/collection/v0_2/utils.py
  bioimageio/spec/commands.py
  bioimageio/spec/partner/utils.py
Labels: documentation

#449 fix rdf_update in resolve_collection_entries
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/collection/v0_2/utils.py
Labels: bug, documentation

#450 Release model RDF 0.4.6
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/model/v0_4/converters.py
  bioimageio/spec/model/v0_4/raw_nodes.py
  example_specs/models/unet2d_nuclei_broad/rdf.yaml
  example_specs/models/unet2d_nuclei_broad/rdf_expand_output_shape.yaml
  tests/conftest.py
Labels: documentation

#452 fix enrich_partial_rdf_with_imjoy_plugin
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/partner/utils.py
Labels: bug, documentation

#456 bump post
  README.md
  bioimageio/spec/VERSION
Labels: documentation

#457 Remove links from titles
  README.md
Labels: documentation, removal

#460 bump post
  README.md
  bioimageio/spec/VERSION
Labels: documentation
