Repository bioimage-io/spec-bioimage-io, pull requests merged in 2024-05, with the labels that each got.

#592 Load from DOI
  README.md
  bioimageio/spec/_internal/io_utils.py
  tests/test_io.py
Labels: documentation

#593 Example notebooks and documentation
  README.md
  example/.ipynb_checkpoints/load_model_and_create_your_own-checkpoint.ipynb
  example/dataset_creation.ipynb
  example/load_model_and_create_your_own.ipynb
  example_use/load_model_and_create_your_own.ipynb
Labels: documentation

#594 Postrelease
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/_internal/field_warning.py
  bioimageio/spec/_internal/io.py
  bioimageio/spec/_internal/io_basics.py
  bioimageio/spec/_internal/io_utils.py
  bioimageio/spec/_internal/types.py
  bioimageio/spec/_internal/url.py
  bioimageio/spec/_internal/validation_context.py
  bioimageio/spec/application/v0_3.py
  bioimageio/spec/collection/v0_3.py
  bioimageio/spec/common.py
  bioimageio/spec/dataset/v0_3.py
  bioimageio/spec/generic/v0_3.py
  bioimageio/spec/model/v0_4.py
  bioimageio/spec/model/v0_5.py
  bioimageio/spec/notebook/v0_3.py
  tests/test_internal/test_io.py
  tests/test_internal/test_types.py
Labels: documentation

#597 remove user documentation links
  bioimageio/spec/application/__init__.py
  bioimageio/spec/collection/__init__.py
  bioimageio/spec/dataset/__init__.py
  bioimageio/spec/generic/__init__.py
  bioimageio/spec/model/__init__.py
  bioimageio/spec/notebook/__init__.py
  scripts/generate_version_submodule_imports.py
Labels: removal

#599 test our axis definitions for ambiguity
  tests/test_model/test_v0_5.py
Labels: testing

#600 Update SPDX license list
  README.md
  bioimageio/spec/_internal/_generated_spdx_license_literals.py
  bioimageio/spec/_internal/constants.py
  bioimageio/spec/static/spdx_licenses.json
  bioimageio/spec/utils.py
  scripts/update_spdx_licenses.py
  scripts/update_spdx_licenses_zenodo.py
Labels: documentation

#603 add timeout to all get requests
  bioimageio/spec/_internal/docs_utils.py
  bioimageio/spec/_internal/field_validation.py
  bioimageio/spec/_internal/io_utils.py
  bioimageio/spec/_internal/url.py
  bioimageio/spec/partner_utils/imjoy/_plugin_parser.py
  scripts/update_spdx_licenses_zenodo.py
Labels: enhancement
