Repository bioimage-io/spec-bioimage-io, pull requests merged in 2024-03, with the labels that each got.

#553 Attempt to fix conda build
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/_internal/io_utils.py
  conda-recipe/meta.yaml
  setup.py
Labels: bug, documentation

#554 patch settings.CI
  .pre-commit-config.yaml
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/_internal/_settings.py
  bioimageio/spec/_internal/io.py
  bioimageio/spec/_internal/types.py
  bioimageio/spec/_internal/version_type.py
  tests/utils.py
Labels: documentation

#557 Optional input tensors
  README.md
  bioimageio/spec/model/v0_5.py
Labels: documentation

#560 Add function to write models directly to streams
  bioimageio/spec/__init__.py
  bioimageio/spec/_internal/io_utils.py
  bioimageio/spec/_package.py
  bioimageio/spec/application/__init__.py
  bioimageio/spec/collection/__init__.py
  bioimageio/spec/dataset/__init__.py
  bioimageio/spec/generic/__init__.py
  bioimageio/spec/model/__init__.py
  bioimageio/spec/notebook/__init__.py
  tests/test_package.py
Labels: enhancement

#562 fix wrong line endings in generated files
  scripts/generate_version_submodule_imports.py
Labels: bug

#564 Add DataDependentSize
  README.md
  bioimageio/spec/_internal/constants.py
  bioimageio/spec/model/v0_5.py
  tests/test_model/test_v0_5.py
Labels: documentation, enhancement

#569 add cache_path env var to settings
  README.md
  bioimageio/spec/__init__.py
  bioimageio/spec/_internal/_settings.py
  bioimageio/spec/_internal/io.py
  tests/test_bioimageio_collection.py
Labels: documentation, enhancement

#568 Binarize along axis
  README.md
  bioimageio/spec/_internal/io.py
  bioimageio/spec/model/v0_5.py
  tests/test_bioimageio_collection.py
Labels: documentation

#571 fix DataDependentSize
  bioimageio/spec/model/v0_5.py
Labels: bug

#567 0.5.1
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/__init__.py
  bioimageio/spec/_internal/_settings.py
  bioimageio/spec/_internal/field_validation.py
  bioimageio/spec/_internal/io.py
  bioimageio/spec/_internal/io_basics.py
  bioimageio/spec/_internal/io_utils.py
  bioimageio/spec/_internal/license_id.py
  bioimageio/spec/_internal/root_url.py
  bioimageio/spec/_internal/types.py
  bioimageio/spec/_internal/url.py
  bioimageio/spec/_internal/validated_string.py
  bioimageio/spec/_internal/validator_annotations.py
  bioimageio/spec/_package.py
  bioimageio/spec/application/v0_2.py
  bioimageio/spec/application/v0_3.py
  bioimageio/spec/collection/v0_2.py
  bioimageio/spec/collection/v0_3.py
  bioimageio/spec/dataset/v0_2.py
  bioimageio/spec/dataset/v0_3.py
  bioimageio/spec/generic/v0_2.py
  bioimageio/spec/generic/v0_3.py
  bioimageio/spec/model/v0_4.py
  bioimageio/spec/model/v0_5.py
  bioimageio/spec/notebook/v0_2.py
  bioimageio/spec/notebook/v0_3.py
  bioimageio/spec/summary.py
  bioimageio/spec/utils.py
  example_descriptions/models/unet2d_nuclei_broad/bioimageio.yaml
  tests/test_bioimageio_collection.py
  tests/test_internal/test_file_source.py
  tests/test_internal/test_license_id.py
  tests/test_internal/test_types.py
  tests/test_internal/test_validated_string.py
  tests/test_model/test_v0_4.py
  tests/test_model/test_v0_5.py
  tests/test_specific_reexports_generics.py
Labels: documentation, enhancement

#574 bump gh actions
  .github/workflows/build.yml
Labels: ci, github_actions

#578 customize pdoc's doc generation
  .github/workflows/build.yml
Labels: ci, github_actions
