Repository bioimage-io/spec-bioimage-io, pull requests merged in 2024-10, with the labels that each got.

#630 Scripts for generating interactive spec docs
  .github/workflows/build.yml
  README.md
  bioimageio/spec/_internal/io.py
  scripts/interactive_docs/__init__.py
  scripts/interactive_docs/__main__.py
  scripts/interactive_docs/hint.py
Labels: documentation, ci, github_actions

#626 switch back to rdf.yaml
  README.md
  bioimageio/spec/_internal/io_basics.py
  tests/test_internal/test_io.py
Labels: documentation

#637 add customizable progressbar and release
  README.md
  bioimageio/spec/VERSION
  bioimageio/spec/__init__.py
  bioimageio/spec/_internal/io.py
Labels: documentation, enhancement

#641 Add module for conda env creation
  bioimageio/spec/_internal/gh_utils.py
  bioimageio/spec/conda_env.py
Labels: enhancement

#643 add code coverage for py3.12 tests
  .github/workflows/build.yml
  pyproject.toml
  setup.py
  tests/test_generic/test_v0_2.py
Labels: enhancement, ci, github_actions, testing

#646 Fix 638
  bioimageio/spec/model/v0_4.py
Labels: bug

#647 Add coverage badge
  .github/workflows/build.yml
  .gitignore
  README.md
Labels: documentation, enhancement, ci, github_actions
